<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Maxime Lestiboudois">

<title>Rapport</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Rapport_files/libs/clipboard/clipboard.min.js"></script>
<script src="Rapport_files/libs/quarto-html/quarto.js"></script>
<script src="Rapport_files/libs/quarto-html/popper.min.js"></script>
<script src="Rapport_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Rapport_files/libs/quarto-html/anchor.min.js"></script>
<link href="Rapport_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Rapport_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Rapport_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Rapport_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Rapport_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Rapport</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Maxime Lestiboudois </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="exercice-1" class="level1">
<h1>Exercice 1</h1>
<p>Le but de cet exercice est de prendre en main les fonctionnalités de R permetant de récupérer des jeux de données, de toutes tailles, très facilement.</p>
<p>Nous utiliserons pour commencer deux fonctions/instructions permettant d’extraire des données d’un fichier texte:<br>
- <code>scan()</code><br>
- <code>read.table()</code></p>
<p><code>scan()</code> permet de récupérer les valeurs d’un fichier lorsqu’elles sont présentées sous forme de liste de valeurs, simplement séparées par un espace. La méthode renvoie alors un objet de type vecteur.<br>
<code>read.table()</code> est utilisé lorsque les données se présentent sous forme de table (une ligne par observation, une colonne par variable).</p>
<section id="partie-a" class="level3">
<h3 class="anchored" data-anchor-id="partie-a">Partie a)</h3>
<p><strong>Enoncé:</strong><br>
Télécharger et copier les données depuis la page Cyberlearn.</p>
<p>Pour cela, il suffit de télécharger les données et de les ajouter dans le dossier Répertoire dans lequel le fichier .R est ouvert. Ici nous ajoutons donc deux nouveaux fichiers à notre répertoire:<br>
- cpus.txt<br>
- examen.txt</p>
<p>Pour connaître le répertoire dans lequel on travaille, on peut utiliser la commande</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">getwd</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "/home/maxx/Documents/HEIG/24-25/PST/R-Project"</code></pre>
</div>
</div>
<p>Pour changer de répertoire, il faut utiliser la commande</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># setwd("MON_NOUVEAU_CHEMIN")</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>MON_NOUVEAU_CHEMIN est le chemin vers le répertoire auquel on souhaite accéder.<br>
La méthode est ici commentée car MON_NOUVEAU_CHEMIN n’est pas un chemin existant les ordinateurs.</p>
</section>
<section id="partie-b" class="level3">
<h3 class="anchored" data-anchor-id="partie-b">Partie b)</h3>
<p><strong>Enoncé:</strong><br>
Charger les données dans R en utilisant les fonctions scan et read.table().<br>
Les utilisateurs se chargeront d’adapter les chemins à leur répertoire de travail et à leur système d’exploitation. Les fichiers cpus.txt et examen.txt sont ainsi accessibles dans R sous les noms cpus et examen respectivement.</p>
<p>En observant les fichiers textes cités ci-dessus, nous nous rendons compte que nous avons affaire à une liste de données pour le fichier cpus.txt et examen.txt est une table de données. Nous utiliserons donc la méthode <code>scan()</code> pour le fichier cpus.txt et <code>read.table()</code> pour examen.txt :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>cpus <span class="ot">&lt;-</span> <span class="fu">scan</span>(<span class="st">"cpus.txt"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>examen <span class="ot">&lt;-</span> <span class="fu">read.table</span>(<span class="st">"examen.txt"</span>, <span class="at">header =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Dans le fichier examen.txt, il y a des en-têtes décrivant les données, le paramètre <em>header</em> vaut alors vrai (TRUE).</p>
</section>
<section id="partie-c" class="level3">
<h3 class="anchored" data-anchor-id="partie-c">Partie c)</h3>
<p><strong>Enoncé:</strong><br>
Pour voir le contenu de l’objet cpus, taper l’instruction :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>cpus</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  62 130  11  12 144  16 133  26  32   7  24  19  24  66 915  92  10  45  12
[20]  58  33  38  38  25 110  40 370 185  22  18 136  44  36  76  66  56 141  64
[39]  36 510  30 100  14  60  46  65  36  21  66  24</code></pre>
</div>
</div>
<p>Idem pour examen:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>examen</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   groupe formation mode_de_formation somme note
1       A        EE                PT  24.5  3.5
2       A        EE                PT  43.5  5.4
3       A        EE                PT  39.5  5.0
4       A        EE                PT  21.5  3.2
5       A        EE                PT  26.5  3.7
6       A        EE                PT  15.5  2.6
7       A        EE                PT  36.0  4.6
8       A        EE                PT  32.0  4.2
9       A        EE                PT  39.0  4.9
10      A        EE                PT  41.5  5.2
11      A        EE                PT  32.0  4.2
12      A        EE                PT  29.5  4.0
13      A        EE                PT  45.0  5.5
14      A        EE                PT  47.5  5.8
15      A        EE                PT  42.5  5.3
16      A        EE                PT  42.0  5.2
17      A        EE                PT  33.0  4.3
18      A        EE                PT  34.0  4.4
19      A        EE                PT  41.0  5.1
20      A        EE                PT  35.0  4.5
21      A        EE                PT  39.5  5.0
22      A        EE                PT  30.0  4.0
23      A        EE                PT  27.5  3.8
24      A        EE                PT  38.5  4.9
25      A        EE                PT  36.0  4.6
26      A        EE                PT  30.0  4.0
27      A        EE                PT  35.5  4.6
28      A        EE                PT  19.5  3.0
29      A        EE                PT  35.0  4.5
30      A        EE                PT  40.0  5.0
31      A        EE                PT  31.5  4.2
32      A        EE                PT  30.0  4.0
33      A        EE                PT  26.5  3.7
34      B        EE                PT  42.5  5.3
35      B        EE                EE  23.0  3.3
36      B        EE                PT    NA   NA
37      B        EE                PT  29.5  4.0
38      B        EE                PT  39.0  4.9
39      B        EE                PT  39.0  4.9
40      B        EE                PT  26.5  3.7
41      B        EE                PT  39.0  4.9
42      B        EE                PT  43.5  5.4
43      B        EE                PT  40.5  5.1
44      B        EE                PT   2.0  1.2
45      B        EE                PT   6.0  1.6
46      B        EE                PT  41.0  5.1
47      B        EE                PT  38.0  4.8
48      B        EE                PT  45.0  5.5
49      B        EE                PT  25.5  3.6
50      B        EE                PT  31.0  4.1
51      B        EE                PT  46.0  5.6
52      B        EE                PT  42.5  5.3
53      B        EE                PT  22.0  3.2
54      B        EE                PT  42.5  5.3
55      B        EE                PT  37.5  4.8
56      B        EE                PT  23.5  3.4
57      B        EE                PT  47.0  5.7
58      B        EE                PT  45.5  5.6
59      B        EE                PT  32.5  4.3
60      B        EE                PT  39.0  4.9
61      B        EE                PT  34.5  4.5
62      B        EE                PT  22.5  3.3
63      B        EE                EE  30.0  4.0
64      B        EE                PT  30.0  4.0
65      B        EE                PT  46.0  5.6
66      B        EE                PT  26.0  3.6
67      B        EE                PT  42.0  5.2
68      B        EE                PT  35.5  4.6
69      B        EE                PT  35.5  4.6
70      B        EE                PT  16.0  2.6
71      B        EE                PT  28.5  3.9
72      B        EE                PT  30.5  4.1
73      B        EE                PT  29.5  4.0
74      B        EE                PT  41.5  5.2
75      B        EE                PT  40.0  5.0
76      B        EE                PT  36.5  4.7
77      B        EE                PT  27.0  3.7</code></pre>
</div>
</div>
</section>
<section id="partie-d" class="level3">
<h3 class="anchored" data-anchor-id="partie-d">Partie d)</h3>
<p><strong>Enoncé:</strong><br>
Pour accéder à la 19ème composante du vecteur cpus, utiliser la commande :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>cpus[<span class="dv">19</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 12</code></pre>
</div>
</div>
<p>Nous obtenons alors la valeur à l’index 19 (la première valeur du vecteur est d’index 1)</p>
</section>
<section id="partie-e" class="level3">
<h3 class="anchored" data-anchor-id="partie-e">Partie e)</h3>
<p><strong>Enoncé:</strong><br>
Pour obtenir une partie du vecteur cpus comme par exemple les éléments du vecteur compris entre la 5ème et la 21ème composante, taper l’instruction :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>cpus[<span class="dv">5</span><span class="sc">:</span><span class="dv">21</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 144  16 133  26  32   7  24  19  24  66 915  92  10  45  12  58  33</code></pre>
</div>
</div>
</section>
<section id="partie-f" class="level3">
<h3 class="anchored" data-anchor-id="partie-f">Partie f)</h3>
<p><strong>Enoncé:</strong><br>
Pour extraire du vecteur cpus ses éléments supérieurs à 200, utiliser la commande :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>cpus[cpus<span class="sc">&gt;</span><span class="dv">200</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 915 370 510</code></pre>
</div>
</div>
</section>
<section id="partie-g" class="level3">
<h3 class="anchored" data-anchor-id="partie-g">Partie g)</h3>
<p><strong>Enoncé:</strong><br>
Il est possible d’accéder directement aux composantes d’une table par le nom. Par exemple, si on veut afficher la composante note de l’objet examen, on peut utiliser la commande :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>examen<span class="sc">$</span>note</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 3.5 5.4 5.0 3.2 3.7 2.6 4.6 4.2 4.9 5.2 4.2 4.0 5.5 5.8 5.3 5.2 4.3 4.4 5.1
[20] 4.5 5.0 4.0 3.8 4.9 4.6 4.0 4.6 3.0 4.5 5.0 4.2 4.0 3.7 5.3 3.3  NA 4.0 4.9
[39] 4.9 3.7 4.9 5.4 5.1 1.2 1.6 5.1 4.8 5.5 3.6 4.1 5.6 5.3 3.2 5.3 4.8 3.4 5.7
[58] 5.6 4.3 4.9 4.5 3.3 4.0 4.0 5.6 3.6 5.2 4.6 4.6 2.6 3.9 4.1 4.0 5.2 5.0 4.7
[77] 3.7</code></pre>
</div>
</div>
</section>
<section id="partie-h" class="level3">
<h3 class="anchored" data-anchor-id="partie-h">Partie h)</h3>
<p><strong>Enoncé:</strong><br>
On peut aussi accéder en profondeur aux composantes comme par exemple par la commande :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>examen<span class="sc">$</span>note[<span class="dv">9</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.9</code></pre>
</div>
</div>
</section>
<section id="partie-i" class="level3">
<h3 class="anchored" data-anchor-id="partie-i">Partie i)</h3>
<p><strong>Enoncé:</strong><br>
La méthode la plus simple pour créer un vecteur consiste à énumérer ses éléments à l’aide de la fonction <em>c()</em> :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a>mesdonnees<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="fl">2.9</span>, <span class="fl">3.4</span>, <span class="fl">3.4</span>, <span class="fl">3.7</span>, <span class="fl">3.7</span>, <span class="fl">2.8</span>, <span class="fl">2.1</span>, <span class="fl">2.5</span>, <span class="fl">2.6</span>, <span class="fl">1.5</span>)</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>mesdonnees</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 2.9 3.4 3.4 3.7 3.7 2.8 2.1 2.5 2.6 1.5</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>couleurs<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="st">"bleu"</span>, <span class="st">"vert"</span>, <span class="st">"blanc"</span>, <span class="st">"noir"</span>, <span class="st">"jaune"</span>)</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>couleurs</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "bleu"  "vert"  "blanc" "noir"  "jaune"</code></pre>
</div>
</div>
</section>
<section id="partie-j" class="level3">
<h3 class="anchored" data-anchor-id="partie-j">Partie j)</h3>
<p><strong>Enoncé:</strong><br>
On peut ôter des composantes d’un vecteur en indiquant entre crochets les indices précédés du signe négatif comme par exemple :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a> mesdonnees[<span class="sc">-</span><span class="fu">c</span>(<span class="dv">5</span><span class="sc">:</span><span class="dv">9</span>)]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.9 3.4 3.4 3.7 1.5</code></pre>
</div>
</div>
</section>
<section id="partie-k" class="level3">
<h3 class="anchored" data-anchor-id="partie-k">Partie k)</h3>
<p><strong>Enoncé:</strong><br>
Finalement, le contenu de votre environnement de travail est affiché à l’aide de la fonction ls() :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ls</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "couleurs"   "cpus"       "examen"     "mesdonnees"</code></pre>
</div>
</div>
</section>
<section id="conclusion-de-lexercice-1" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-de-lexercice-1">Conclusion de l’exercice 1</h2>
<p>Dans cet exercice, nous avons appris à :<br>
- changer de répertoire de travail<br>
- extraire des jeux de données de fichiers textes<br>
- afficher les dits-jeuc de données<br>
- accèder à certaines parties uniquement de vecteurs ou tables de données<br>
- créer des vecteurs de données<br>
- modifier des données présentes dans les vecteurs<br>
- afficher le contenu de notre environnement de travail</p>
</section>
</section>
<section id="exercice-2" class="level1">
<h1>Exercice 2</h1>
<p>La performance relative au processeur IBM 370/158-3 de 50 processeurs d’ordinateurs a été relevée.</p>
<p>L’objet cpus contient les valeurs observées:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>cpus</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  62 130  11  12 144  16 133  26  32   7  24  19  24  66 915  92  10  45  12
[20]  58  33  38  38  25 110  40 370 185  22  18 136  44  36  76  66  56 141  64
[39]  36 510  30 100  14  60  46  65  36  21  66  24</code></pre>
</div>
</div>
<section id="partie-a-1" class="level3">
<h3 class="anchored" data-anchor-id="partie-a-1">Partie a)</h3>
<p><strong>Enoncé:</strong><br>
Construire un diagramme branche-et-feuilles, une boîte à moustaches et un histogramme des données observées à l’aide des commandes ci-dessous.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stem</span>(cpus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
  The decimal point is 2 digit(s) to the right of the |

  0 | 111111222222223333344444445566666777789
  1 | 01334449
  2 | 
  3 | 7
  4 | 
  5 | 1
  6 | 
  7 | 
  8 | 
  9 | 2</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="at">pty=</span><span class="st">"s"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(cpus, <span class="at">xlab=</span><span class="st">"performance relative"</span>, <span class="at">col=</span><span class="st">"darkslategray4"</span>, <span class="at">horizontal=</span>T) </span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(cpus)</span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(cpus, <span class="at">xlab=</span><span class="st">"performance relative"</span>, <span class="at">ylab=</span><span class="st">"fréquence"</span>, <span class="at">main=</span><span class="st">""</span>, </span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"darkslategray4"</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rapport_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="quels-sont-les-effet-de-cette-commande" class="level4">
<h4 class="anchored" data-anchor-id="quels-sont-les-effet-de-cette-commande">1) Quels sont les effet de cette commande?</h4>
<p>Laquelle?</p>
</section>
<section id="quel-est-leffet-de-la-fonction-rug" class="level4">
<h4 class="anchored" data-anchor-id="quel-est-leffet-de-la-fonction-rug">2) Quel est l’effet de la fonction <code>rug()</code>?</h4>
<p>La fonction <strong><code>rug()</code></strong> en R ajoute de “petites barres verticales” (ou des “traits”) le long de l’axe des x (ou y) pour représenter individuellement chaque observation des données. L’effet principal de cette fonction est de permettre la visualisation de la densité des données de manière précise directement sur un graphique en montrant exactement où se trouvent la valeurs observées.<br>
La fonction <code>rug()</code>a comme avantages de fournir une information granulaire qui complète les graphiques résumés, de montrer si certaines données sont concentrées ou dispersées et enfin aide grandement à repérer les valeurs isolées ou des regroupements locaux.</p>
</section>
<section id="observer-les-résultats-obtenus-par-chaque-commande." class="level4">
<h4 class="anchored" data-anchor-id="observer-les-résultats-obtenus-par-chaque-commande.">Observer les résultats obtenus par chaque commande.</h4>
<p><strong>stem(cpus)</strong><br>
Cette commande génère un diagramme branche-et-feuilles pour les données de cpus. Elle divise les données en une partie “tige” (les chiffres significatifs, comme les dizaines) et une partie “feuille” (les unités). Cela fournit une visualisation textuelle rapide pour comprendre la répartition et les valeurs individuelles des données.</p>
<p><strong>par(mfrow=c(1,2), pty=“s”)</strong><br>
<code>par(mfrow=c(1,2))</code> divise la fenêtre graphique en une rangée de deux colonnes (1 ligne, 2 colonnes), permettant d’afficher deux graphiques côte à côte.<code>pty="s"</code> ajuste les graphiques pour qu’ils aient un rapport d’aspect carré.</p>
<p><strong>boxplot(cpus, xlab=“performance relative”, col=“darkslategray4”, horizontal=T)</strong><br>
Trace une boîte à moustaches (boxplot) des données. Elle permet une visualisation de la médiane, des quartiles (Q1 et Q3), des valeurs extrêmes (whiskers), et éventuellement des points aberrants.</p>
<p>Le paramètre <code>horizontal=T</code> rend le boxplot horizontal, le paramètre <code>col="darkslategray4"</code> modifie la couleur de la boîte. Enfin, le paramètre <code>xlab="performance relative"</code> ajoute une étiquette descriptive à l’axe x.</p>
<p><strong>rug(cpus)</strong><br>
La fonction rug() ajoute de petites barres verticales le long de l’axe horizontal dans le boxplot, représentant chaque observation dans les données. Cela permet de visualiser individuellement les valeurs des données, en plus des statistiques résumées fournies par le boxplot.</p>
<p><strong>hist(cpus, xlab=“performance relative”, ylab=“fréquence”, main=““, col=”darkslategray4”)</strong><br>
Cette commande trace un histogramme des données de l’objet cpus. Les valeurs de cpus sont alors regroupées en classe. La hauteur de chaque barre représente la fréquence des observation dans chaque classe.<br>
Les étiquette d’axes (<code>xlab</code> et <code>ylab</code>) et la couleur des barres (<code>col="darkslategray4</code>) sont personnalisées.<br>
<code>main=""</code> laisse le titre vide</p>
<p><strong>par(mfrow=c(1,1))</strong> Cette commande réinitialise la dispositon graphique pour revenir à un seul graphique par fenêtre.</p>
<p><strong>Résumé des commandes combinées</strong><br>
Cette suite de commandes crée une visualisation complète des données :<br>
1) Diagramme branche-et-feuilles pour une vue textuelle. 2) Boîte à moustaches pour un résumé des statistiques et des valeurs aberrantes.<br>
3) Histogramme pour une vue des fréquences des données.<br>
4) <code>rug()</code> dans le boxplot pour montrer individuellement chaque donnée.<br>
Ces visualisations offrent à la fois un aperçu statistique (boîte à moustaches) et une distribution (histogramme et diagramme branche-et-feuilles) des données cpus.</p>
</section>
</section>
<section id="partie-b-1" class="level3">
<h3 class="anchored" data-anchor-id="partie-b-1">Partie b)</h3>
<p><strong>Enoncé:</strong><br>
Commenter la distribution des valeurs observées en se basant sur les graphiques de la Figure 1 : valeur(s) atypique(s), asymétrie.</p>
<p><strong>Valeurs atypiques:</strong><br>
Dans la boîte à moustaches, les valeurs atypiques sont identifiées comme des points en dehors des “moustaches”.<br>
Nous remarquons ici que les données 915 et 510 sont très éloignées du reste de la distribution et donc se démarquent fortement.</p>
<p><strong>Asymétrie:</strong><br>
Principalement visible dans l’histogramme, on remarque une asymétrie forte vers la gauche. La majorité des valeurs sont inférieures à 100 et restent donc groupées dans une même barre. Seules quelques valeurs sont dispersées dans les autres barres de l’histogramme.<br>
La boîte à moustache confirme cette asymétrie : la médiane est décalée vers la gauche, et la moustache supérieure est beaucoup plus longue que l’inférieure.</p>
<p><strong>Répartition des données:</strong><br>
Les données sont majoritairement concentrées dans une plage étroite (entre 10 et 100, comme le montre le boxplot et l’histogramme). Cela suggère une densité élevée dans cette région.<br>
Quelques observations exceptionnelles (915, 510, etc.) sont situées bien au-delà du reste des données, créant une queue longue dans la distribution.</p>
</section>
<section id="partie-c-1" class="level3">
<h3 class="anchored" data-anchor-id="partie-c-1">Partie c)</h3>
<p><strong>Enoncé:</strong><br>
Calculer la performance relative médiane et la performance relative moyenne des valeurs observées en utilisant les fonctions de R adéquates.</p>
<p>Pour calculer la performance relative médiane, nous utilisons la fonction <code>median()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a> <span class="fu">median</span>(cpus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 42</code></pre>
</div>
</div>
<p>Pour calculer la performance moyenne, nous utilison la fonction <code>mean()</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(cpus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 86.88</code></pre>
</div>
</div>
<p><strong>Question:</strong><br>
Est-il plus approprié d’utiliser la médiane ou la moyenne ?</p>
<p>Nous remarquons que la médiane des données est moins sensible aux valeurs atypiques et représente la valeur centrale des performances relatives.<br>
La moyenne des données est influencée par les valeurs extrêmes (atypiques), ce qui pourrait la tirer vers des valeurs plus élevées que la médiane.</p>
<p>Ici, nous pouvons donc indiquer que la médiane est un indicateur plus approprié que la moyenne car elle offre une mesure plus robuste et réaliste. La moyenne peut cependant être utile pour compléter l’analyse, indiquant notamment l’impact des valeurs atypiques.</p>
</section>
<section id="partie-d-1" class="level3">
<h3 class="anchored" data-anchor-id="partie-d-1">Partie d)</h3>
<p><strong>Enoncé:</strong><br>
Déterminer le(s) mode(s) des valeurs observées à l’aide des commandes suivantes :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>n.cpus<span class="ot">&lt;-</span><span class="fu">table</span>(cpus)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">as.numeric</span>(<span class="fu">names</span>(n.cpus)[n.cpus<span class="sc">==</span><span class="fu">max</span>(n.cpus)])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 24 36 66</code></pre>
</div>
</div>
<p>On observe donc plusieurs modes, les données sont donc multimodales.</p>
</section>
<section id="partie-e-1" class="level3">
<h3 class="anchored" data-anchor-id="partie-e-1">Partie e)</h3>
<p><strong>Enoncé:</strong><br>
Que fait la commande suivante ?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(cpus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
   7.00   24.00   42.00   86.88   73.50  915.00 </code></pre>
</div>
</div>
<p>Cette commande rend un “tableau” avec les valeurs suivantes:</p>
<ul>
<li><p>Min : représente la plus petite valeur contenue dans l’objet cpus</p></li>
<li><p>1st Qu. : soit le premier quartile. C’est la limite inférieure sur un graphique de type boîte à moustache.</p></li>
<li><p>Median : représente la médiane, soit la valeur centrale de la distribution</p></li>
<li><p>Mean : représente la moyenne arithmétique des données</p></li>
<li><p>3rd Qu. : soit le troisème quartile. C’est la limite supérieure sur un graphique de type boîte à moustache.</p></li>
<li><p>Max : représente la plus grande valeur contenue dans l’objet cpus</p></li>
</ul>
</section>
<section id="partie-f-1" class="level3">
<h3 class="anchored" data-anchor-id="partie-f-1">Partie f)</h3>
<p><strong>Enoncé:</strong> Décrire l’effet sur la moyenne et sur la médiane des trois interventions suivantes :<br>
1. ajouter un processeur de performance relative 43<br>
2. soustraire 9 à chaque valeur observée<br>
3. diviser chaque observation par 3</p>
<p><strong>1)</strong><br>
La moyenne est directement affectée par l’ajout de nouvelles valeurs.<br>
Cela augmente la somme totale des observations (de 43 ici) et augmente le nombre total d’observation (de 1 ici).<br>
Pour calculer la nouvelle moyenne, on peut utiliser la formule suivante:<br>
<span class="math display">\[Nouvelle Moyenne = (Ancienne Somme Totale + 43) / (Ancien Nombre Observations + 1) \]</span> Si la valeur ajoutée est proche de l’ancienne moyenne, l’effet sera minime.</p>
<p>La médiane est moins sensible que la moyenne. Elle ne sera modifiée que si la nouvelle valeur affecte la position de la valeur centrale.</p>
<p><strong>2)</strong><br>
La moyenne et la médiane sont affectées de manière linéaire si on soustrait un coefficient équivalent à chacune des observations du jeu de données. On peut utiliser les formules suivantes pour trouver les nouvelles moyenne et médiane respectivement:<br>
<span class="math display">\[NouvelleMoyenne = Ancienne Moyenne - 9 \]</span> <span class="math display">\[Nouvelle Mediane = Ancienne Mediane - 9\]</span></p>
<p><strong>3)</strong><br>
Comme pour le point 2), la médiane et la moyenne sont affectées de la même manière lorsque les observations sont divisées par 3: Elles sont également divisées par 3. On peut alors utiliser les formules suivantes: <span class="math display">\[NouvelleMoyenne = Ancienne Moyenne / 3  \]</span> <span class="math display">\[Nouvelle Mediane = Ancienne Mediane / 3\]</span></p>
</section>
<section id="partie-g-1" class="level3">
<h3 class="anchored" data-anchor-id="partie-g-1">Partie g)</h3>
<p><strong>Enoncé:</strong><br>
Calculer l’écart-type des performances relatives une fois avec les valeurs atypiques et une fois sans en utilisant la fonction sd(). Les valeurs atypiques peuvent être déterminées à l’aide de la fonction boxplot() avec plot=FALSE comme argument.</p>
<p>Calcul de l’écart-type avec les valeurs atypiques:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(cpus)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 148.4294</code></pre>
</div>
</div>
<p>Identification des valeurs atypiques:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>box <span class="ot">&lt;-</span> <span class="fu">boxplot</span>(cpus, <span class="at">plot =</span> <span class="cn">FALSE</span>);</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>box</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$stats
     [,1]
[1,]    7
[2,]   24
[3,]   42
[4,]   76
[5,]  144

$n
[1] 50

$conf
         [,1]
[1,] 30.38082
[2,] 53.61918

$out
[1] 915 370 185 510

$group
[1] 1 1 1 1

$names
[1] "1"</code></pre>
</div>
</div>
<p>Les valeurs atypiques sont répertoriées sous la banière <code>out</code>. Nous pouvons donc les récupérer en utilisant la commande suivante:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>valeursAtypiques <span class="ot">&lt;-</span> box<span class="sc">$</span>out</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>valeursAtypiques</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 915 370 185 510</code></pre>
</div>
</div>
<p>Nous pouvons ensuite les retirer de notre jeu de données (en faisant une copie pour ne pas corrompre notre jeu initial):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>cpus_clean <span class="ot">&lt;-</span> cpus[<span class="sc">!</span>cpus <span class="sc">%in%</span> valeursAtypiques]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Calcul de l’écart-type sans les valeurs atypiques:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(cpus_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 38.5864</code></pre>
</div>
</div>
<p><strong>Question</strong><br>
Que constate-t-on ? L’écart-type est-il un indicateur robuste ?</p>
<p>L’écart-type n’est pas un indicateur robuste. Les valeurs atypiques ont une grande influence sur sa valeur. On remarque dans nos résultats une différence de 109.843, ce qui est absolument énorme.</p>
</section>
<section id="exercice-3" class="level2">
<h2 class="anchored" data-anchor-id="exercice-3">Exercice 3</h2>
<p>Les étudiants suivant un cours de Probabilités et Statistique dans une école d’ingénierie ont passé l’examen de fin d’unité. Le cours était donné par le même professeur à étudiants répartis en deux groupes notés A et B. Les résultats obtenus figurent dans la table ci-dessous et sont contenus dans l’objet examen.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>examen</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   groupe formation mode_de_formation somme note
1       A        EE                PT  24.5  3.5
2       A        EE                PT  43.5  5.4
3       A        EE                PT  39.5  5.0
4       A        EE                PT  21.5  3.2
5       A        EE                PT  26.5  3.7
6       A        EE                PT  15.5  2.6
7       A        EE                PT  36.0  4.6
8       A        EE                PT  32.0  4.2
9       A        EE                PT  39.0  4.9
10      A        EE                PT  41.5  5.2
11      A        EE                PT  32.0  4.2
12      A        EE                PT  29.5  4.0
13      A        EE                PT  45.0  5.5
14      A        EE                PT  47.5  5.8
15      A        EE                PT  42.5  5.3
16      A        EE                PT  42.0  5.2
17      A        EE                PT  33.0  4.3
18      A        EE                PT  34.0  4.4
19      A        EE                PT  41.0  5.1
20      A        EE                PT  35.0  4.5
21      A        EE                PT  39.5  5.0
22      A        EE                PT  30.0  4.0
23      A        EE                PT  27.5  3.8
24      A        EE                PT  38.5  4.9
25      A        EE                PT  36.0  4.6
26      A        EE                PT  30.0  4.0
27      A        EE                PT  35.5  4.6
28      A        EE                PT  19.5  3.0
29      A        EE                PT  35.0  4.5
30      A        EE                PT  40.0  5.0
31      A        EE                PT  31.5  4.2
32      A        EE                PT  30.0  4.0
33      A        EE                PT  26.5  3.7
34      B        EE                PT  42.5  5.3
35      B        EE                EE  23.0  3.3
36      B        EE                PT    NA   NA
37      B        EE                PT  29.5  4.0
38      B        EE                PT  39.0  4.9
39      B        EE                PT  39.0  4.9
40      B        EE                PT  26.5  3.7
41      B        EE                PT  39.0  4.9
42      B        EE                PT  43.5  5.4
43      B        EE                PT  40.5  5.1
44      B        EE                PT   2.0  1.2
45      B        EE                PT   6.0  1.6
46      B        EE                PT  41.0  5.1
47      B        EE                PT  38.0  4.8
48      B        EE                PT  45.0  5.5
49      B        EE                PT  25.5  3.6
50      B        EE                PT  31.0  4.1
51      B        EE                PT  46.0  5.6
52      B        EE                PT  42.5  5.3
53      B        EE                PT  22.0  3.2
54      B        EE                PT  42.5  5.3
55      B        EE                PT  37.5  4.8
56      B        EE                PT  23.5  3.4
57      B        EE                PT  47.0  5.7
58      B        EE                PT  45.5  5.6
59      B        EE                PT  32.5  4.3
60      B        EE                PT  39.0  4.9
61      B        EE                PT  34.5  4.5
62      B        EE                PT  22.5  3.3
63      B        EE                EE  30.0  4.0
64      B        EE                PT  30.0  4.0
65      B        EE                PT  46.0  5.6
66      B        EE                PT  26.0  3.6
67      B        EE                PT  42.0  5.2
68      B        EE                PT  35.5  4.6
69      B        EE                PT  35.5  4.6
70      B        EE                PT  16.0  2.6
71      B        EE                PT  28.5  3.9
72      B        EE                PT  30.5  4.1
73      B        EE                PT  29.5  4.0
74      B        EE                PT  41.5  5.2
75      B        EE                PT  40.0  5.0
76      B        EE                PT  36.5  4.7
77      B        EE                PT  27.0  3.7</code></pre>
</div>
</div>
<p>On se demande si une différence significative existe entre les deux groupes à l’examen.</p>
<section id="partie-a-2" class="level3">
<h3 class="anchored" data-anchor-id="partie-a-2">Partie a)</h3>
<p><strong>Enoncé:</strong><br>
Tracer les boîtes à moustaches en parallèle en utilisant les commandes suivantes :</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>lblue<span class="ot">&lt;-</span><span class="st">"#528B8B"</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">pty=</span><span class="st">"s"</span>)</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(note<span class="sc">~</span>groupe, <span class="at">data=</span>examen, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">6</span>), <span class="at">xlab=</span><span class="st">"groupe"</span>, </span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">varwidth=</span>T, <span class="at">col=</span>lblue, <span class="at">main=</span><span class="st">"examen"</span>)</span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">4</span>, <span class="at">lty=</span><span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rapport_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="partie-b-2" class="level3">
<h3 class="anchored" data-anchor-id="partie-b-2">Partie b)</h3>
<p><strong>Enoncé:</strong><br>
Rajouter les bâtonnets des notes des étudiants des deux classes, sur le côté gauche des boîtes à moustaches pour la classe (side=2 comme argument de la fonction <code>rug()</code>) et sur le côté droite pour la classe (side=4 comme argument de la fonction <code>rug()</code>).<br>
<em>Indication:</em> pour séparer puis enregistrer les notes des étudiants selon les groupes, on peut utiliser les commandes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>note.A<span class="ot">&lt;-</span><span class="fu">split</span>(examen<span class="sc">$</span>note, examen<span class="sc">$</span>groupe)<span class="sc">$</span>A</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>note.B<span class="ot">&lt;-</span><span class="fu">split</span>(examen<span class="sc">$</span>note, examen<span class="sc">$</span>groupe)<span class="sc">$</span>B</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Rajoutons les bâtonnets au graphique:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>lblue<span class="ot">&lt;-</span><span class="st">"#528B8B"</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">pty=</span><span class="st">"s"</span>)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(note<span class="sc">~</span>groupe, <span class="at">data=</span>examen, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">6</span>), <span class="at">xlab=</span><span class="st">"groupe"</span>, </span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">varwidth=</span>T, <span class="at">col=</span>lblue, <span class="at">main=</span><span class="st">"examen"</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="dv">4</span>, <span class="at">lty=</span><span class="dv">2</span>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(note.A, <span class="at">side=</span><span class="dv">2</span>)  </span>
<span id="cb55-7"><a href="#cb55-7" aria-hidden="true" tabindex="-1"></a><span class="fu">rug</span>(note.B, <span class="at">side=</span><span class="dv">4</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Rapport_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="partie-c-2" class="level3">
<h3 class="anchored" data-anchor-id="partie-c-2">Partie c)</h3>
<p><strong>Enoncé:</strong><br>
En se basant sur la Figure 2 (ci-dessus), existe-t-il une différence significative entre les deux groupes à l’examen de fin d’unité ?</p>
<p>On remarque que la boîte du groupe B est légérement plus étendue que celle du groupe A. On peut donc supposer que la distribution des notes a été plus éparse que pour le groupe A. On remarque ……</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>